# -*- coding: utf-8 -*-
"""Assignment #9: Lists

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YRUnDLCnicKehcUfvSVX85d_OOlDvjQQ

def for sodoku grid
"""

def sodoku_grid():
  '''
  This function will take a user's sodoku input, and return if it is a valid grid or not.

  Inputs: user's sodoku grid

  Output: If the user's grid is valid or not.
  '''
  # for user to enter their grid:
  user_grid = input("Enter your sodoku grid: ")

  # Step #1 = convert input to a list of numbers using the 'replace' method:
  # this will get rid of whitespace, commas, brackets:
  grid = user_grid.replace(" ", "").replace("[", "").replace("]", "").replace(",", "")

  # this will convert the grid (user_grid) to a string of nums
  # iterate through each character in the string (grid), and make sure it's a real number:
  nums = [int(char) for char in grid if char.isdigit()]

  # Step 2: make sure the nums are 1 <= num <= 9 for valid sodoku:
  # = check if all numbers are within the range 1 - 9 (if not all nums are between 1 and 9, then it is invalid for sodoku):
  if not all(1 <= num <= 9 for num in nums):
    print("Invalid. All numbers in the sodoku must be between 1 and 9.")

  # Step 3: make sure there are 9 UNIQUE elements using len(set(nums)), which will order the numbers in set by unique elements (should == 9):
  if len(set(nums)) != 9:
    print("Invalid. There must be at least 9 UNIQUE elements in a sodoku grid.")
  else:
    print("The sodoku grid is valid.")

"""def for number of unique words:"""

def count_common_words():
  '''
  This function will take a user's string input, and return the number of unique words, and the number of words that occur the most within the passage.

  The input is the user's passage.

  The output is the number of unique words, and the words that occur the most often within the user's input string.
  '''
  # for the user to enter the passage:
  user_passage = input("Enter the passage you would like to analyze: ")

  # this is to split the user's input into individual words using the '.split' method:
  passage_words = user_passage.split()

  # this is to count all of the words in the passage, and to store them into a list for later:
  # innitialize the word count dictionary (i don't know how else to do this besides using a dict)
  passage_word_count = {}
  for word in passage_words:
    # this will count the words from the dict and innitialize the count to zero and add one for every time it is in the passage_word_count dict:
    passage_word_count[word] = passage_word_count.get(word, 0) + 1

  # using the 'len' function, it will automatically count the number of unique words in the user's string:
  unique_passage_words = len(set(passage_words))
  # to print it in an 'astetically pleasing' way:
  print("________________________________________________")
  print(f"Number of unique words in the passage: {unique_passage_words}")
  print("________________________________________________")

  # this is to give the user the option to see the most commonly occuring words:
  common_words = input("Would you like to see the number of times the most common words occur? ('y/n'): ")
  if common_words == 'y':
    # most common = max numbers from the passage word count dict as above = '.values' function and 'max' function:
    max_common_words = max(passage_word_count.values())
    # to print:
    print(f"The most commonly occuring word(s) from the passage occur {max_common_words} times in the passage.")
  else:
    print("ok")

"""MAIN"""

while True:
  # for user to chose the program
  program_choice = input("Enter the program you would like to run: ('s' for analyze sodoku or 'c' for count passage words: )")

  # in case user enters an invalid program choice
  if program_choice != 's' and program_choice != 'c':
    print("Invalid choice. Please try again. ")
    continue

  # FOR ANALYZING SODOKU GRID:
  elif program_choice == 's':
    while True:
      sodoku_grid()
      run_sodoku = input("Run again? ('y/n'):")
      if run_sodoku != 'y':
        break

  # FOR COUNTING THE PASSAGE WORDS:
  elif program_choice == 'c':
    while True:
      count_common_words()
      run_count = input("Run again? ('y/n'): ")
      if run_count != 'y':
        break

  # invlaid choice
  else:
    print("invalid choice. Please try again. /n")
    continue

# run program again (while loop)
  run_program_again = input("Would you like to run the program again? ('y' for yes, 'stop' to exit): ")
  if run_program_again != 'y':
    break